'use strict';
const crypto=require('crypto');
const {pool}=require('../config/db');
const drawRepo=require('../repositories/drawRepository');
const {buildTicket,createSeededRng,drawRandomNumbers,drawWeightedNumbers,matchTier}=require('../domain/drawEngine');
const {settleDraw,verifyConservation}=require('../domain/prizeEngine');
const CONFIG_VERSION='v1'; const ALGORITHM_VERSION='seeded-prng-v1';
class DrawError extends Error{constructor(message,code='DRAW_ERROR',status=400){super(message);this.code=code;this.status=status;}}
function validateMonth(month){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw new DrawError('month must be in YYYY-MM format','INVALID_MONTH',400);}
function hashSnapshot(entries,month,strategy){const normalized=[...entries].sort((a,b)=>String(a.userId).localeCompare(String(b.userId))).map(e=>({userId:e.userId,ticket:e.ticket,scoreDates:e.scoreDates}));return crypto.createHash('sha256').update(JSON.stringify({month,strategy,entries:normalized})).digest('hex');}
async function buildEligibleEntries(client){const rows=await drawRepo.listEligibleEntries(client);return rows.map(r=>({userId:r.user_id,ticket:buildTicket(r.values.map(Number)),scoreDates:r.score_dates}));}
async function simulateDraw(month,strategy,options={}){validateMonth(month);if(!['random','algorithmic'].includes(strategy))throw new DrawError('strategy must be "random" or "algorithmic"','INVALID_STRATEGY');const client=await pool.connect();try{await client.query('BEGIN');if(await drawRepo.findPublishedDraw(month,client))throw new DrawError(`${month} has already been published and is immutable`,'ALREADY_PUBLISHED',409);let draw=await drawRepo.findDraftDraw(month,client);const seed=options.seed||crypto.randomBytes(16).toString('hex');if(draw){await drawRepo.clearComputedRows(draw.id,client);draw=await drawRepo.updateDraftSeed(client,draw.id,seed,strategy);}else draw=await drawRepo.createDraft(month,strategy,seed,client);const entries=await buildEligibleEntries(client);const snapshotHash=hashSnapshot(entries,month,strategy);await drawRepo.insertEntries(client,draw.id,entries);const rng=createSeededRng(seed);const winningNumbers=strategy==='algorithmic'?drawWeightedNumbers(entries.map(e=>e.ticket),rng):drawRandomNumbers(rng);await drawRepo.insertResult(client,draw.id,winningNumbers);const winnersByTier={5:[],4:[],3:[]};for(const e of entries){const tier=matchTier(e.ticket,winningNumbers);if(tier)winnersByTier[tier].push(e.userId);}const totalPoolMinor=await drawRepo.totalPoolForMonth(month,client);const carry=await drawRepo.previousPublishedDraw(month,client);const jackpotCarryIn=Number(carry.jackpot_carry_out||0);const settlement=settleDraw(totalPoolMinor,winnersByTier,jackpotCarryIn);if(!verifyConservation(totalPoolMinor,jackpotCarryIn,settlement))throw new DrawError('Prize conservation check failed — aborting','CONSERVATION_FAILED',500);const winnerRows=[];for(const tier of [5,4,3])for(const userId of settlement.payouts[tier].winnerIds)winnerRows.push({userId,tier,payoutMinor:settlement.payouts[tier].payoutPerWinner});const insertedWinners=await drawRepo.insertWinners(client,draw.id,winnerRows);const updatedDraw=await drawRepo.markSimulated(client,draw.id,{totalPoolMinor,jackpotCarryIn,jackpotCarryOut:settlement.carryOutJackpot,unawardedMinor:settlement.unawardedMinor,snapshotHash,seed,algorithmVersion:ALGORITHM_VERSION,configVersion:CONFIG_VERSION});await client.query('COMMIT');return{draw:updatedDraw,winningNumbers,winners:insertedWinners,entryCount:entries.length,tierPools:settlement.tierPools,seed,snapshotHash};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function publishDraw(drawId){const client=await pool.connect();try{await client.query('BEGIN');const draw=await drawRepo.lockDrawForUpdate(client,drawId);if(!draw)throw new DrawError('Draw not found','NOT_FOUND',404);if(draw.status==='published')throw new DrawError('This draw has already been published','ALREADY_PUBLISHED',409);if(draw.status!=='simulated')throw new DrawError('Run a simulation before publishing','NOT_SIMULATED',400);const earlier=await drawRepo.findEarlierUnpublishedDraw(draw.month,client);if(earlier)throw new DrawError(`Cannot publish ${draw.month} before ${earlier.month} is published`,'OUT_OF_ORDER_PUBLISH',409);const published=await drawRepo.markPublished(client,drawId);await client.query('COMMIT');return published;}catch(e){await client.query('ROLLBACK');if(e.code==='23505')throw new DrawError('This month has already been published','ALREADY_PUBLISHED',409);throw e;}finally{client.release();}}
async function getDraw(drawId){const d=await drawRepo.findFullDrawById(drawId);if(!d){const e=new DrawError('Draw not found','NOT_FOUND',404);throw e;}return d;}
async function listPublicDraws(userId){return drawRepo.listPublishedDraws({userId});}
async function getPublicDraw(drawId,userId){const d=await drawRepo.findPublicDraw(drawId,userId);if(!d){const e=new DrawError('Draw not found','NOT_FOUND',404);throw e;}return d;}
module.exports={simulateDraw,publishDraw,getDraw,listPublicDraws,getPublicDraw,hashSnapshot,DrawError};
