'use strict';
const crypto=require('crypto');const winnerRepo=require('../repositories/winnerRepository');const storage=require('../config/supabaseStorage');const {detectImageType,expectedMimeType}=require('../utils/imageValidation');
const MAX_FILE_BYTES=5*1024*1024;
class WinnerError extends Error{constructor(message,code='WINNER_ERROR',status=400){super(message);this.code=code;this.status=status;}}
async function listMyWinnings(userId){return winnerRepo.listMine(userId);}
async function listAllWinners(status){return winnerRepo.listAll({status});}
async function uploadProof(userId,winnerId,file){if(!file)throw new WinnerError('A proof image is required','FILE_REQUIRED');if(file.size>MAX_FILE_BYTES)throw new WinnerError('Image must be 5MB or smaller','FILE_TOO_LARGE');const type=detectImageType(file.buffer);if(!type)throw new WinnerError('Uploaded file content is not a valid PNG, JPEG, or WEBP image','INVALID_FILE_CONTENT');const expected=expectedMimeType(type);if(file.mimetype!==expected)throw new WinnerError('File MIME type does not match its image content','INVALID_FILE_TYPE');const winner=await winnerRepo.findOwned(winnerId,userId);if(!winner){const e=new Error('Winner record not found');e.status=404;throw e;}if(winner.status==='paid')throw new WinnerError('This prize has already been paid — proof can no longer be changed','ALREADY_PAID',409);const path=`${winnerId}/${Date.now()}-${crypto.randomBytes(6).toString('hex')}.${type}`;await storage.uploadPrivateFile(path,file.buffer,file.mimetype);return winnerRepo.insertProof(userId,winnerId,path);}
async function getProofSignedUrl(winnerId,user){const winner=await winnerRepo.findById(winnerId);if(!winner||(user.role!=='admin'&&winner.user_id!==user.id)){const e=new Error('Winner record not found');e.status=404;throw e;}const proof=await winnerRepo.findLatestProof(winnerId);if(!proof){const e=new Error('No proof uploaded yet');e.status=404;throw e;}return{url:await storage.getSignedUrl(proof.storage_path),status:proof.status,versionNo:proof.version_no};}
async function reviewProof(winnerId,decision,adminId){if(!['approved','rejected'].includes(decision))throw new WinnerError('decision must be "approved" or "rejected"','INVALID_DECISION');const winner=await winnerRepo.findById(winnerId);if(!winner){const e=new Error('Winner record not found');e.status=404;throw e;}if(winner.status==='paid')throw new WinnerError('A paid winner cannot have its proof workflow changed','ALREADY_PAID',409);const proof=await winnerRepo.findLatestProof(winnerId);if(!proof){const e=new Error('No proof uploaded for this winner yet');e.status=404;throw e;}return winnerRepo.reviewProof(proof.id,decision,adminId);}
async function markPaid(winnerId){const winner=await winnerRepo.findById(winnerId);if(!winner){const e=new Error('Winner record not found');e.status=404;throw e;}if(winner.status==='paid')throw new WinnerError('Already paid','ALREADY_PAID',409);const proof=await winnerRepo.findLatestProof(winnerId);if(!proof||proof.status!=='approved')throw new WinnerError('Payout requires an approved proof first','PROOF_NOT_APPROVED');const updated=await winnerRepo.markPaid(winnerId);if(!updated)throw new WinnerError('Payout could not be completed','PAYOUT_FAILED',409);return updated;}
module.exports={listMyWinnings,listAllWinners,uploadProof,getProofSignedUrl,reviewProof,markPaid,detectImageType,WinnerError};
