'use strict';
const {pool}=require('../config/db');
async function listUsers(){const {rows}=await pool.query(`SELECT u.id,u.email,u.role,u.created_at,s.status AS subscription_status,s.charity_id FROM users u LEFT JOIN LATERAL(SELECT status,charity_id FROM subscriptions WHERE user_id=u.id ORDER BY CASE WHEN status='active' AND (current_period_end IS NULL OR current_period_end > now()) THEN 0 ELSE 1 END,created_at DESC LIMIT 1)s ON true ORDER BY u.created_at DESC`);return rows;}
async function getUserDetail(id){const {rows}=await pool.query(`SELECT id,email,role,created_at FROM users WHERE id=$1`,[id]);return rows[0]||null;}
async function updateUserProfile(id,{email}){const normalized=email===undefined?undefined:String(email).trim().toLowerCase();try{const {rows}=await pool.query(`UPDATE users SET email=COALESCE($1,email) WHERE id=$2 RETURNING id,email,role,created_at`,[normalized,id]);return rows[0]||null;}catch(e){if(e.code==='23505'){e.status=409;e.code='EMAIL_TAKEN';e.message='Email is already in use';}throw e;}}
async function setUserRole(id,role){if(!['subscriber','admin'].includes(role)){const e=new Error('role must be subscriber or admin');e.status=400;throw e;}const {rows}=await pool.query(`UPDATE users SET role=$1 WHERE id=$2 RETURNING id,email,role`,[role,id]);return rows[0]||null;}
async function listSubscriptions(){const {rows}=await pool.query(`SELECT s.*,u.email,p.name AS plan_name,p.interval,c.name AS charity_name FROM subscriptions s JOIN users u ON u.id=s.user_id JOIN plans p ON p.id=s.plan_id LEFT JOIN charities c ON c.id=s.charity_id ORDER BY s.created_at DESC`);return rows;}
async function listUserScores(userId){const {rows}=await pool.query(`SELECT id,TO_CHAR(score_date,'YYYY-MM-DD') AS date,value FROM scores WHERE user_id=$1 ORDER BY score_date DESC`,[userId]);return {scores:rows};}
async function reportsSummary(){const [users,active,funding,payouts,jackpot,unawarded,charity,draws]=await Promise.all([pool.query(`SELECT COUNT(*)::int AS count FROM users`),pool.query(`SELECT COUNT(*)::int AS count FROM subscriptions WHERE status='active' AND (current_period_end IS NULL OR current_period_end > now())`),pool.query(`SELECT COALESCE(SUM(pool_minor),0)::bigint AS total FROM charity_contributions`),pool.query(`SELECT COALESCE(SUM(payout_minor),0)::bigint AS total FROM winners`),pool.query(`SELECT COALESCE((SELECT jackpot_carry_out FROM draws WHERE status='published' ORDER BY month DESC LIMIT 1),0)::bigint AS total`),pool.query(`SELECT COALESCE(SUM(unawarded_minor),0)::bigint AS total FROM draws WHERE status='published'`),pool.query(`SELECT COALESCE(SUM(charity_minor),0)::bigint AS total FROM charity_contributions`),pool.query(`SELECT month,status,total_pool_minor,jackpot_carry_in,jackpot_carry_out,unawarded_minor,(SELECT COUNT(*) FROM winners WHERE draw_id=draws.id)::int AS winner_count FROM draws ORDER BY month DESC LIMIT 12`)]);return {totalUsers:users.rows[0].count,activeSubscribers:active.rows[0].count,totalPrizePoolFunding:Number(funding.rows[0].total),totalPayouts:Number(payouts.rows[0].total),currentJackpotRollover:Number(jackpot.rows[0].total),totalUnawarded:Number(unawarded.rows[0].total),totalCharityContributions:Number(charity.rows[0].total),drawStatistics:draws.rows};}
async function getConfig(){const {rows}=await pool.query(`SELECT key,value FROM platform_settings WHERE key IN ('pool_contribution_pct','tier_shares') ORDER BY key`);return Object.fromEntries(rows.map(r=>[r.key,r.value]));}
async function updateConfig(poolContributionPct){const {rows}=await pool.query(`INSERT INTO platform_settings(key,value) VALUES('pool_contribution_pct',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now() RETURNING key,value`,[poolContributionPct]);return rows[0];}
module.exports={listUsers,getUserDetail,updateUserProfile,setUserRole,listSubscriptions,listUserScores,reportsSummary,getConfig,updateConfig};
