'use strict';
const {pool}=require('../config/db');
async function list({search,includeInactive=false}={}){const params=[];const clauses=[];if(!includeInactive)clauses.push('c.is_active=true');if(search){params.push(`%${search}%`);clauses.push(`(c.name ILIKE $${params.length} OR c.description ILIKE $${params.length})`);}const {rows}=await pool.query(`SELECT c.id,c.name,c.description,c.min_pct,c.images,c.is_active FROM charities c ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY c.name`,params);return rows;}
async function findById(id,{includeInactive=false}={},client=pool){const {rows}=await client.query(`SELECT id,name,description,min_pct,images,is_active FROM charities WHERE id=$1 ${includeInactive?'':'AND is_active=true'}`,[id]);return rows[0]||null;}
async function findAdminById(id){const {rows}=await pool.query(`SELECT id,name,description,min_pct,images,is_active FROM charities WHERE id=$1`,[id]);return rows[0]||null;}
async function eventsForCharity(id,client=pool){const {rows}=await client.query(`SELECT id,title,event_date AS date,description FROM charity_events WHERE charity_id=$1 ORDER BY event_date NULLS LAST,id`,[id]);return rows;}
async function mediaForCharity(id,client=pool){const {rows}=await client.query(`SELECT id,media_type,url,title FROM charity_media WHERE charity_id=$1 ORDER BY id`,[id]);return rows;}
async function create({name,description,minPct=10,images=[]}){const {rows}=await pool.query(`INSERT INTO charities(name,description,min_pct,images) VALUES($1,$2,$3,$4) RETURNING *`,[name,description,minPct,images]);return rows[0];}
async function update(id,{name,description,minPct,images,isActive}){const {rows}=await pool.query(`UPDATE charities SET name=COALESCE($1,name),description=COALESCE($2,description),min_pct=COALESCE($3,min_pct),images=COALESCE($4,images),is_active=COALESCE($5,is_active) WHERE id=$6 RETURNING *`,[name,description,minPct,images,isActive,id]);return rows[0]||null;}
async function deactivate(id){const {rows}=await pool.query(`UPDATE charities SET is_active=false WHERE id=$1 RETURNING *`,[id]);return rows[0]||null;}
async function createEvent(charityId,{title,date,description}){const {rows}=await pool.query(`INSERT INTO charity_events(charity_id,title,event_date,description) VALUES($1,$2,$3,$4) RETURNING id,title,event_date AS date,description`,[charityId,title,date||null,description||null]);return rows[0];}
async function updateEvent(id,{title,date,description}){const {rows}=await pool.query(`UPDATE charity_events SET title=COALESCE($1,title),event_date=COALESCE($2,event_date),description=COALESCE($3,description) WHERE id=$4 RETURNING id,title,event_date AS date,description`,[title,date,description,id]);return rows[0]||null;}
async function removeEvent(id){const r=await pool.query(`DELETE FROM charity_events WHERE id=$1`,[id]);return r.rowCount>0;}
async function createMedia(charityId,{mediaType,url,title}){const {rows}=await pool.query(`INSERT INTO charity_media(charity_id,media_type,url,title) VALUES($1,$2,$3,$4) RETURNING *`,[charityId,mediaType||'image',url,title||null]);return rows[0];}
async function removeMedia(id){const r=await pool.query(`DELETE FROM charity_media WHERE id=$1`,[id]);return r.rowCount>0;}
module.exports={list,findById,findAdminById,eventsForCharity,mediaForCharity,create,update,deactivate,createEvent,updateEvent,removeEvent,createMedia,removeMedia};
