'use strict';
const {pool}=require('../config/db');
async function listEligibleEntries(client=pool){const {rows}=await client.query(`SELECT u.id AS user_id,ARRAY_AGG(sc.value ORDER BY sc.score_date DESC) AS values,ARRAY_AGG(sc.score_date ORDER BY sc.score_date DESC) AS score_dates FROM users u JOIN subscriptions s ON s.user_id=u.id JOIN scores sc ON sc.user_id=u.id WHERE s.status='active' AND (s.current_period_end IS NULL OR s.current_period_end > now()) GROUP BY u.id HAVING COUNT(sc.id)=5 ORDER BY u.id`);return rows;}
async function totalPoolForMonth(month,client=pool){const {rows}=await client.query(`SELECT COALESCE(SUM(pool_minor),0)::bigint AS total FROM charity_contributions WHERE billing_period=$1`,[month]);return Number(rows[0].total);}
async function previousPublishedDraw(month,client=pool){const {rows}=await client.query(`SELECT jackpot_carry_out FROM draws WHERE status='published' AND month < $1 ORDER BY month DESC LIMIT 1`,[month]);return rows[0]||{jackpot_carry_out:0};}
async function findDraftDraw(month,client=pool){const {rows}=await client.query(`SELECT * FROM draws WHERE month=$1 AND status IN ('draft','simulated') ORDER BY id DESC LIMIT 1`,[month]);return rows[0]||null;}
async function findPublishedDraw(month,client=pool){const {rows}=await client.query(`SELECT * FROM draws WHERE month=$1 AND status='published' LIMIT 1`,[month]);return rows[0]||null;}
async function findEarlierUnpublishedDraw(month,client=pool){const {rows}=await client.query(`SELECT month,status FROM draws WHERE month < $1 AND status <> 'published' ORDER BY month ASC LIMIT 1`,[month]);return rows[0]||null;}
async function createDraft(month,strategy,seed,client=pool){const {rows}=await client.query(`INSERT INTO draws(month,strategy,status,seed,algorithm_version,config_version) VALUES($1,$2,'draft',$3,'seeded-prng-v1','v1') RETURNING *`,[month,strategy,seed]);return rows[0];}
async function clearComputedRows(drawId,client){await client.query(`DELETE FROM winners WHERE draw_id=$1`,[drawId]);await client.query(`DELETE FROM draw_results WHERE draw_id=$1`,[drawId]);await client.query(`DELETE FROM draw_entries WHERE draw_id=$1`,[drawId]);await client.query(`UPDATE draws SET snapshot_hash=NULL,status='draft' WHERE id=$1`,[drawId]);}
async function updateDraftSeed(client,drawId,seed,strategy){const {rows}=await client.query(`UPDATE draws SET seed=$1,strategy=$2 WHERE id=$3 AND status IN ('draft','simulated') RETURNING *`,[seed,strategy,drawId]);return rows[0];}
async function insertEntries(client,drawId,entries){for(const e of entries){if(!e.ticket.length||e.ticket.length>5||e.ticket.some(n=>!Number.isInteger(n)||n<1||n>45)||e.scoreDates?.length!==5)throw new Error('Invalid frozen draw entry');await client.query(`INSERT INTO draw_entries(draw_id,user_id,ticket_numbers,score_dates) VALUES($1,$2,$3,$4)`,[drawId,e.userId,e.ticket,e.scoreDates]);}}
async function insertResult(client,drawId,winningNumbers){const {rows}=await client.query(`INSERT INTO draw_results(draw_id,winning_numbers) VALUES($1,$2) RETURNING *`,[drawId,winningNumbers]);return rows[0];}
async function insertWinners(client,drawId,winners){const inserted=[];for(const w of winners){const {rows}=await client.query(`INSERT INTO winners(draw_id,draw_entry_id,user_id,tier,payout_minor,status) VALUES($1,(SELECT id FROM draw_entries WHERE draw_id=$1 AND user_id=$2),$2,$3,$4,'pending') RETURNING id,draw_id,draw_entry_id,user_id,tier,payout_minor,status`,[drawId,w.userId,w.tier,w.payoutMinor]);inserted.push(rows[0]);}return inserted;}
async function markSimulated(client,drawId,fields){const {rows}=await client.query(`UPDATE draws SET status='simulated',total_pool_minor=$1,jackpot_carry_in=$2,jackpot_carry_out=$3,unawarded_minor=$4,snapshot_hash=$5,seed=$6,algorithm_version=$7,config_version=$8 WHERE id=$9 RETURNING *`,[fields.totalPoolMinor,fields.jackpotCarryIn,fields.jackpotCarryOut,fields.unawardedMinor,fields.snapshotHash,fields.seed,fields.algorithmVersion,fields.configVersion,drawId]);return rows[0];}
async function lockDrawForUpdate(client,drawId){const {rows}=await client.query(`SELECT * FROM draws WHERE id=$1 FOR UPDATE`,[drawId]);return rows[0]||null;}
async function markPublished(client,drawId){const {rows}=await client.query(`UPDATE draws SET status='published',published_at=now() WHERE id=$1 RETURNING *`,[drawId]);return rows[0];}
async function findFullDrawById(drawId,client=pool){const dr=await client.query(`SELECT * FROM draws WHERE id=$1`,[drawId]);const draw=dr.rows[0];if(!draw)return null;const rr=await client.query(`SELECT winning_numbers FROM draw_results WHERE draw_id=$1`,[drawId]);const wr=await client.query(`SELECT w.id,w.draw_entry_id,w.user_id,u.email,w.tier,w.payout_minor,w.status FROM winners w JOIN users u ON u.id=w.user_id WHERE w.draw_id=$1 ORDER BY w.tier DESC,w.id`,[drawId]);const er=await client.query(`SELECT user_id,ticket_numbers,score_dates FROM draw_entries WHERE draw_id=$1 ORDER BY user_id`,[drawId]);return {...draw,winningNumbers:rr.rows[0]?.winning_numbers||null,winners:wr.rows,entries:er.rows};}
async function listPublishedDraws({userId=null}={},client=pool){const params=[];let extra='';if(userId){params.push(userId);extra=`,(SELECT json_build_object('entryId',de.id,'ticketNumbers',de.ticket_numbers) FROM draw_entries de WHERE de.draw_id=d.id AND de.user_id=$1 LIMIT 1) AS my_entry,(SELECT json_agg(json_build_object('id',w.id,'tier',w.tier,'payoutMinor',w.payout_minor,'status',w.status) ORDER BY w.tier DESC) FROM winners w WHERE w.draw_id=d.id AND w.user_id=$1) AS my_winnings`;}const {rows}=await client.query(`SELECT d.id,d.month,d.status,d.strategy,d.published_at,d.total_pool_minor,d.jackpot_carry_out,d.unawarded_minor,(SELECT winning_numbers FROM draw_results dr WHERE dr.draw_id=d.id) AS winning_numbers${extra} FROM draws d WHERE d.status='published' ORDER BY d.month DESC`,params);return rows;}
async function findPublicDraw(drawId,userId=null,client=pool){
  const params=userId?[drawId,userId]:[drawId];
  const privateSql=userId?`,(SELECT json_build_object('entryId',de.id,'ticketNumbers',de.ticket_numbers) FROM draw_entries de WHERE de.draw_id=d.id AND de.user_id=$2 LIMIT 1) AS my_entry,(SELECT json_agg(json_build_object('id',w.id,'tier',w.tier,'payoutMinor',w.payout_minor,'status',w.status) ORDER BY w.tier DESC) FROM winners w WHERE w.draw_id=d.id AND w.user_id=$2) AS my_winnings`:'';
  const {rows}=await client.query(`SELECT d.id,d.month,d.status,d.strategy,d.published_at,d.total_pool_minor,d.jackpot_carry_out,d.unawarded_minor,(SELECT winning_numbers FROM draw_results dr WHERE dr.draw_id=d.id) AS winning_numbers${privateSql} FROM draws d WHERE d.id=$1 AND d.status='published'`,params);
  return rows[0]||null;
}
module.exports={listEligibleEntries,totalPoolForMonth,previousPublishedDraw,findDraftDraw,findPublishedDraw,findEarlierUnpublishedDraw,createDraft,clearComputedRows,updateDraftSeed,insertEntries,insertResult,insertWinners,markSimulated,lockDrawForUpdate,markPublished,findFullDrawById,listPublishedDraws,findPublicDraw};
