'use strict';
const {pool}=require('../config/db');
async function findPlan(planId,client=pool){const {rows}=await client.query(`SELECT id,name,interval,price_minor,currency FROM plans WHERE id=$1`,[planId]);return rows[0]||null;}
async function listPlans(){const {rows}=await pool.query(`SELECT id,name,interval,price_minor,currency FROM plans ORDER BY CASE WHEN interval='month' THEN 0 ELSE 1 END,id`);return rows;}
async function getSetting(key,client=pool){const {rows}=await client.query(`SELECT value FROM platform_settings WHERE key=$1`,[key]);return rows[0]?rows[0].value:null;}
async function findByUser(userId){const {rows}=await pool.query(`SELECT id,user_id,plan_id,stripe_customer_id,stripe_subscription_id,status,charity_id,charity_pct,pool_pct_snapshot,current_period_start,current_period_end FROM subscriptions WHERE user_id=$1 ORDER BY CASE WHEN status='active' AND (current_period_end IS NULL OR current_period_end > now()) THEN 0 ELSE 1 END, created_at DESC LIMIT 1`,[userId]);return rows[0]||null;}
async function findEntitledByUser(userId){const {rows}=await pool.query(`SELECT * FROM subscriptions WHERE user_id=$1 AND status='active' AND (current_period_end IS NULL OR current_period_end > now()) ORDER BY created_at DESC LIMIT 1`,[userId]);return rows[0]||null;}
async function findByStripeSubscriptionId(id,client=pool){const {rows}=await client.query(`SELECT * FROM subscriptions WHERE stripe_subscription_id=$1`,[id]);return rows[0]||null;}
async function upsertFromCheckout(client,data){const {rows}=await client.query(`INSERT INTO subscriptions(user_id,plan_id,stripe_customer_id,stripe_subscription_id,status,charity_id,charity_pct,pool_pct_snapshot,current_period_start,current_period_end) VALUES($1,$2,$3,$4,'active',$5,$6,$7,$8,$9) ON CONFLICT(stripe_subscription_id) DO UPDATE SET status='active',stripe_customer_id=EXCLUDED.stripe_customer_id,plan_id=EXCLUDED.plan_id,charity_id=EXCLUDED.charity_id,charity_pct=EXCLUDED.charity_pct,pool_pct_snapshot=EXCLUDED.pool_pct_snapshot,current_period_start=COALESCE(EXCLUDED.current_period_start,subscriptions.current_period_start),current_period_end=COALESCE(EXCLUDED.current_period_end,subscriptions.current_period_end) RETURNING *`,[data.userId,data.planId,data.stripeCustomerId,data.stripeSubscriptionId,data.charityId,data.charityPct,data.poolPctSnapshot,data.currentPeriodStart,data.currentPeriodEnd]);return rows[0];}
async function updatePeriodAndStatus(client,id,{status,currentPeriodStart,currentPeriodEnd}){const {rows}=await client.query(`UPDATE subscriptions SET status=$1,current_period_start=COALESCE($2,current_period_start),current_period_end=COALESCE($3,current_period_end) WHERE stripe_subscription_id=$4 RETURNING *`,[status,currentPeriodStart,currentPeriodEnd,id]);return rows[0]||null;}
async function insertHistory(client,subscriptionId,eventType,snapshot){await client.query(`INSERT INTO subscription_history(subscription_id,event_type,effective_at,snapshot) VALUES($1,$2,now(),$3)`,[subscriptionId,eventType,snapshot]);}
async function insertContribution(client,{subscriptionId,billingPeriod,grossMinor,charityMinor,poolMinor,charityId,charityPct,poolPct,allocationBasis,stripeInvoiceId}){const {rows}=await client.query(`INSERT INTO charity_contributions(subscription_id,billing_period,gross_minor,charity_minor,pool_minor,charity_id,charity_pct,pool_pct,allocation_basis,stripe_invoice_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(subscription_id,billing_period) DO NOTHING RETURNING *`,[subscriptionId,billingPeriod,grossMinor,charityMinor,poolMinor,charityId,charityPct,poolPct,allocationBasis,stripeInvoiceId||null]);return rows[0]||null;}
async function claimStripeEvent(client,eventId,type){try{await client.query(`INSERT INTO stripe_events(event_id,type) VALUES($1,$2)`,[eventId,type]);return true;}catch(e){if(e.code==='23505')return false;throw e;}}
async function listAll(){const {rows}=await pool.query(`SELECT s.*,u.email,p.name AS plan_name,p.interval,c.name AS charity_name FROM subscriptions s JOIN users u ON u.id=s.user_id JOIN plans p ON p.id=s.plan_id LEFT JOIN charities c ON c.id=s.charity_id ORDER BY s.created_at DESC`);return rows;}
async function ensureAnnualPeriodContributions(client,month){const {rows}=await client.query(`INSERT INTO charity_contributions(subscription_id,billing_period,gross_minor,charity_minor,pool_minor,charity_id,charity_pct,pool_pct,allocation_basis) SELECT s.id,$1,ROUND(p.price_minor/12.0)::int,FLOOR((ROUND(p.price_minor/12.0)::int*s.charity_pct)/100)::int,FLOOR((ROUND(p.price_minor/12.0)::int*s.pool_pct_snapshot)/100)::int,s.charity_id,s.charity_pct,s.pool_pct_snapshot,'annual-monthly-equivalent' FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE p.interval='year' AND s.status='active' AND s.current_period_start IS NOT NULL AND s.current_period_end IS NOT NULL AND s.current_period_start < (($1||'-01')::date + INTERVAL '1 month') AND s.current_period_end >= (($1||'-01')::date) ON CONFLICT(subscription_id,billing_period) DO NOTHING RETURNING id`,[month]);return rows.length;}
async function updateSetting(key,value){const {rows}=await pool.query(`INSERT INTO platform_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now() RETURNING key,value,updated_at`,[key,value]);return rows[0];}
module.exports={findPlan,listPlans,getSetting,findByUser,findEntitledByUser,findByStripeSubscriptionId,upsertFromCheckout,updatePeriodAndStatus,insertHistory,insertContribution,claimStripeEvent,listAll,ensureAnnualPeriodContributions,updateSetting};
