'use strict';
const {pool}=require('../config/db');
async function findById(id){const {rows}=await pool.query(`SELECT * FROM winners WHERE id=$1`,[id]);return rows[0]||null;}
async function findOwned(id,userId){const {rows}=await pool.query(`SELECT * FROM winners WHERE id=$1 AND user_id=$2`,[id,userId]);return rows[0]||null;}
async function listMine(userId){const {rows}=await pool.query(`SELECT w.*,d.month,lp.id AS proof_id,lp.status AS proof_status FROM winners w JOIN draws d ON d.id=w.draw_id LEFT JOIN LATERAL (SELECT wp.id,wp.status FROM winner_proofs wp WHERE wp.winner_id=w.id ORDER BY wp.version_no DESC LIMIT 1) lp ON true WHERE w.user_id=$1 ORDER BY w.created_at DESC`,[userId]);return rows;}
async function listAll({status}={}){const params=[];let where='';if(status){params.push(status);where='WHERE w.status=$1';}const {rows}=await pool.query(`SELECT w.*,d.month,u.email,lp.id AS proof_id,lp.status AS proof_status,lp.storage_path AS proof_storage_path FROM winners w JOIN draws d ON d.id=w.draw_id JOIN users u ON u.id=w.user_id LEFT JOIN LATERAL (SELECT wp.id,wp.status,wp.storage_path FROM winner_proofs wp WHERE wp.winner_id=w.id ORDER BY wp.version_no DESC LIMIT 1) lp ON true ${where} ORDER BY w.created_at DESC`,params);return rows;}
async function findLatestProof(winnerId){const {rows}=await pool.query(`SELECT * FROM winner_proofs WHERE winner_id=$1 ORDER BY version_no DESC LIMIT 1`,[winnerId]);return rows[0]||null;}
async function insertProof(userId,winnerId,storagePath){const client=await pool.connect();try{await client.query('BEGIN');const w=await client.query(`SELECT id,user_id,status FROM winners WHERE id=$1 FOR UPDATE`,[winnerId]);if(!w.rowCount||w.rows[0].user_id!==userId)throw Object.assign(new Error('Winner record not found'),{status:404});const max=await client.query(`SELECT COALESCE(MAX(version_no),0)+1 AS next FROM winner_proofs WHERE winner_id=$1`,[winnerId]);const {rows}=await client.query(`INSERT INTO winner_proofs(winner_id,user_id,version_no,storage_path,status) VALUES($1,$2,$3,$4,'pending') RETURNING *`,[winnerId,userId,max.rows[0].next,storagePath]);await client.query('COMMIT');return rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function reviewProof(proofId,status,adminId){const {rows}=await pool.query(`UPDATE winner_proofs SET status=$1,reviewed_by=$2,reviewed_at=now() WHERE id=$3 RETURNING *`,[status,adminId,proofId]);return rows[0]||null;}
async function markPaid(winnerId){const {rows}=await pool.query(`UPDATE winners SET status='paid' WHERE id=$1 AND status='pending' RETURNING *`,[winnerId]);return rows[0]||null;}
module.exports={findById,findOwned,listMine,listAll,findLatestProof,insertProof,reviewProof,markPaid};
