import { useEffect, useState } from 'react';
import { endpoints } from '../api/endpoints';
import { extractApiError } from '../api/client';
import SectionHeading from '../components/SectionHeading';
import Loading from '../components/Loading';
import Alert from '../components/Alert';
import Badge from '../components/Badge';
import Button from '../components/Button';
import AdminNav from '../components/AdminNav';
import { formatMoney, formatMonth, statusLabel } from '../lib/format';

export default function AdminWinnersPage() {
  const [rows, setRows] = useState([]); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  async function load() { setLoading(true); try { const r = await endpoints.winners.adminList(status); setRows(r.data.winners || []); } catch (e) { setError(extractApiError(e, 'Could not load winners.')); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [status]);
  async function review(id, decision) { if (!window.confirm(`${decision === 'approved' ? 'Approve' : 'Reject'} this proof?`)) return; setBusy(id); setError(''); try { await endpoints.winners.review(id, decision); await load(); } catch (e) { setError(extractApiError(e, 'Could not review proof.')); } finally { setBusy(''); } }
  async function paid(id) { if (!window.confirm('Mark this approved winner as paid?')) return; setBusy(id); setError(''); try { await endpoints.winners.paid(id); await load(); } catch (e) { setError(extractApiError(e, 'Could not mark payout.')); } finally { setBusy(''); } }
  async function proof(id) { const popup = window.open('', '_blank', 'noopener,noreferrer'); if (!popup) { setError('Allow popups for this site to open proof images.'); return; } try { const r = await endpoints.winners.proof(id); popup.location = r.data.url; popup.opener = null; } catch (e) { popup.close(); setError(extractApiError(e, 'Could not open proof.')); } }
  if (loading) return <Loading label="Loading winner queue..." />;
  return <div><AdminNav /><SectionHeading eyebrow="Administration" title="Winner review" description="Review the latest private proof version. A payout can only be marked paid after an approved proof." action={<select aria-label="Filter winner status" value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm text-white"><option value="">All winners</option><option value="pending">Pending payout</option><option value="paid">Paid</option></select>} />{error && <Alert>{error}</Alert>}<section className="overflow-hidden rounded-3xl border border-white/10 bg-white/[0.035]"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead><tr className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><th className="px-4 py-4">Draw</th><th className="px-4 py-4">User</th><th className="px-4 py-4">Tier</th><th className="px-4 py-4">Payout</th><th className="px-4 py-4">Winner</th><th className="px-4 py-4">Proof</th><th className="px-4 py-4">Actions</th></tr></thead><tbody>{rows.map((w) => <tr key={w.id} className="border-b border-white/5"><td className="px-4 py-4 text-slate-400">{formatMonth(w.month)}</td><td className="px-4 py-4 text-slate-200">{w.email}</td><td className="px-4 py-4 text-white">{w.tier}/5</td><td className="px-4 py-4 text-slate-300">{formatMoney(w.payout_minor)}</td><td className="px-4 py-4"><Badge tone={w.status === 'paid' ? 'green' : 'yellow'}>{statusLabel(w.status)}</Badge></td><td className="px-4 py-4"><Badge tone={w.proof_status === 'approved' ? 'green' : w.proof_status === 'rejected' ? 'red' : 'yellow'}>{statusLabel(w.proof_status) || 'Not uploaded'}</Badge></td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{w.proof_id && <Button variant="secondary" onClick={() => proof(w.id)}>Proof</Button>}{w.proof_id && w.status !== 'paid' && <><Button variant="ghost" disabled={busy === w.id} onClick={() => review(w.id, 'approved')}>Approve</Button><Button variant="danger" disabled={busy === w.id} onClick={() => review(w.id, 'rejected')}>Reject</Button></>}{w.status !== 'paid' && w.proof_status === 'approved' && <Button disabled={busy === w.id} onClick={() => paid(w.id)}>Mark paid</Button>}</div></td></tr>)}</tbody></table></div></section></div>;
}
