import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const features = [
  ['01', 'Choose a cause', 'Browse participating charities, read their stories, and choose where your charity contribution goes.'],
  ['02', 'Keep your scorecard ready', 'Maintain your latest five Stableford scores. Five retained scores make an account draw-eligible.'],
  ['03', 'Check the monthly draw', 'Published results show the winning numbers, prize pool and any personal winnings.'],
];

export default function HomePage() {
  const { user } = useAuth();
  return <div className="space-y-16">
    <section className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-cyan-400/10 via-slate-900 to-indigo-400/10 p-7 md:p-12"><div className="hero-grid absolute inset-0 opacity-70" /><div className="relative grid gap-10 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Play with purpose</p><h1 className="max-w-4xl text-5xl font-semibold leading-[0.98] tracking-[-0.04em] text-white md:text-7xl">Your game can support a cause.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 md:text-lg">Digital Heroes brings charitable contribution together with a monthly prize draw. Pick a charity, keep your latest five scores ready, and follow each published draw.</p><div className="mt-8 flex flex-wrap gap-3"><Link to={user ? '/dashboard' : '/signup'} className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-slate-200">{user ? 'Open dashboard' : 'Get started'}</Link><Link to="/charities" className="rounded-xl border border-white/15 bg-white/[0.04] px-5 py-3 text-sm font-semibold text-white hover:bg-white/[0.08]">Explore charities</Link></div></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{[['5','scores retained'],['3','winning tiers'],['10%','minimum charity share']].map(([value,label])=><div key={label} className="rounded-2xl border border-white/10 bg-black/20 p-4 backdrop-blur"><p className="text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>)}</div></div></section>
    <section><div className="mb-7 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">How it works</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-white">A simple route from scorecard to impact.</h2></div><div className="grid gap-4 md:grid-cols-3">{features.map(([number,title,description])=><article key={number} className="card-sheen rounded-3xl border border-white/10 bg-white/[0.035] p-6"><p className="text-xs font-semibold text-slate-500">{number}</p><h3 className="mt-9 text-xl font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p></article>)}</div></section>
    <section className="grid gap-5 lg:grid-cols-3"><div className="rounded-3xl border border-white/10 bg-white/[0.025] p-7"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Prize tiers</p><div className="mt-5 grid grid-cols-3 gap-3">{[['5','40%'],['4','35%'],['3','25%']].map(([tier,share])=><div key={tier} className="rounded-2xl border border-white/10 bg-slate-950/30 p-4 text-center"><p className="text-2xl font-semibold text-white">{tier}</p><p className="mt-1 text-xs text-slate-400">matches · {share}</p></div>)}</div><p className="mt-5 text-sm leading-6 text-slate-400">Multiple winners split the applicable tier equally. Only an unclaimed five-match jackpot rolls forward.</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.025] p-7 lg:col-span-2"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Transparency</p><h2 className="mt-2 text-2xl font-semibold text-white">Payment and prize state stay on the server.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Stripe handles card details. Subscription lifecycle is finalized from verified webhook events, while draw results, payouts and winner ownership are resolved by the backend. Winner proof remains private until an authorized request obtains its signed URL.</p><Link to="/draws" className="mt-6 inline-flex rounded-xl border border-white/15 px-4 py-2.5 text-sm font-medium text-white hover:bg-white/5">View published draws →</Link></div></section>
  </div>;
}
